### PR TITLE
Move ceph-salt-registry-json creation outside bootstrap

### PR DESCRIPTION
**Pull request by tserong**
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1187015
Signed-off-by: Tim Serong <tserong@suse.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
Do you want to replace things with `--registry-json`? https://docs.ceph.com/en/latest/cephadm/install/?highlight=registry%20login#further-information-about-cephadm-bootstrap

**Comment by smithfarm** [comment]
For me, it's confusing to have something in "cephbootstrap.sls" that has been "moved outside bootstrap". Syntactically speaking, I understand that it will probably work that way, but just in the interests of having meaningful names, I would suggest to move the code into a completely different sls file. It could be called "cephsaltregistryjson.sls", for example.

**Comment by tserong** [comment]
> Do you want to replace things with `--registry-json`

Ah, yeah, looks like we've missed one of them. We do currently have `cephadm bootstrap --registry-json /tmp/ceph-salt-registry-json` and `ceph cephadm registry-login -i /tmp/ceph-salt-registry-json`, but the earlier `cephadm registry-login` is still using the old form where it passes registry, username and password via the CLI. I'll fix that too.

> For me, it's confusing to have something in "cephbootstrap.sls" that has been "moved outside bootstrap". Syntactically speaking, I understand that it will probably work that way, but just in the interests of having meaningful names, I would suggest to move the code into a completely different sls file. It could be called "cephsaltregistryjson.sls", for example.

Totally fair, will rejig.

**Comment by tserong** [comment]
Alright, that ought to be a bit cleaner.

**Comment by sebastian-philipp** [comment]
https://github.com/ceph/ceph/pull/43889#issuecomment-970231254

**Comment by tserong** [comment]
(Jenkins failure looks to me like Jenkins itself is broken - see also https://ceph-ci.suse.de/blue/organizations/jenkins/sesdev-integration/detail/master/1095/pipeline/, assuming I've got that URL correct)

**Review by smithfarm — APPROVED** [review]

**Pull request merged**
