### PR TITLE
Add "status" command

### LINKED ISSUE #7: Implement `status` command
The `ceph-bootstrap status` command should preform some validations to guarantee that ceph-bootstrap can work correctly in the installed system, and show the status of those checks, and if something fails, suggest possible actions to users.

List of validations:
- Salt
    - check if salt-master package is installed, or just that salt-master is available (it might be installed from source)
    - check if we can communicate with the salt-master, execute operations, etc...
- ceph-salt-formula
    - check if package is installed (it should be if ceph-bootstrap was installed through the RPM)
    - check if state files are present
    - check if salt pillar is correctly configured by looking at `top.sls` file
        - if not, it should suggest to run `ceph-bootstrap init` (Issue #8) that should take care of making sure
          the pillar gets correctly configured.
- Config
  - check that at least one minion is both 'mgr' and 'mon'

### PR DESCRIPTION
**Pull request by ricardoasmarques**
`ceph-salt status` command will check if Salt is correctly configured and if the current configuration is valid.
Additionally, `ceph-salt deploy` command will also check if current configuration is valid.

**Example:**
Screenshot from 2020-03-03 23-23-58

Fixes: https://github.com/ceph/ceph-salt/issues/7

Signed-off-by: Ricardo Marques <rimarques@suse.com>

### CODE REVIEW

**Comment by bk201** [comment]
Test with sesdev:
```
sesdev create octopus --roles="[admin], [mon], [mgr], [storage]" --ceph-salt-repo https://github.com/ricardoasmarques/ceph-salt.git --ceph-salt-branch wip-status --stop-before-ceph-salt-deploy dev2
```

The `ceph-salt status` works as description when there is no node acts as Mgr and Mon
```
admin:~ # ceph-salt status
At least one minion must be both 'Mgr' and 'Mon'
```

But the deploy command can't reach the check:
```
admin:~ # ceph-salt -ldebug deploy --non-interactive
Checking if ceph-salt formula is available...
salt-master will be restarted to load ceph-salt formula
Could not find ceph-salt formula. Please check if ceph-salt-formula package is installed
```

**Comment by ricardoasmarques** [comment]
> ...
> But the deploy command can't reach the check:
> 
> ```
> admin:~ # ceph-salt -ldebug deploy --non-interactive
> Checking if ceph-salt formula is available...
> salt-master will be restarted to load ceph-salt formula
> Could not find ceph-salt formula. Please check if ceph-salt-formula package is installed
> ```

@bk201 the check you are facing happens before the config validation, so I think this is not related to this PR.

Check if all minions are returning "True" when executing:

[1]
```
salt -G 'ceph-salt:member' state.sls_exists ceph-salt
```

If no, check if `salt-minion` service is running in all minions:

```
systemctl status salt-minion
```

Try to restart `salt-master` service manually, and check [1] again:

```
systemctl restart salt-master
```

**Comment by smithfarm** [comment]
@ricardoasmarques With `ceph-salt deploy` there is a `--non-interactive` switch which, among other things, prevents ceph-salt from emitting VT-style escape sequences that, in an interactive setting, do nice things like display colors, but elsewhere (like when being run by an automated tool like sesdev and teuthology) have the effect of adding lots of noise - in the form of raw escape sequences - to the log.

Does this new command `ceph-salt status` have a similar option for turning off the escape sequences?

**Comment by bk201** [comment]
> 
> @bk201 the check you are facing happens before the config validation, so I think this is not related to this PR.

Thanks! I checked again and It's actually the undefined variable `bootstrap_minion` in pillar (as the minion log in https://github.com/ceph/ceph-salt/issues/84) makes minions reply error when running `salt -G 'ceph-salt:member' state.sls_exists ceph-salt`. So it can't reach the check here yet to print useful message: https://github.com/ceph/ceph-salt/pull/112/files#diff-d5595865bb360e37be437f3b1446834cR1268-R1273

**Comment by ricardoasmarques** [comment]
> ...
> Does this new command `ceph-salt status` have a similar option for turning off the escape sequences?

@smithfarm I've added a `-n`/`--no-color` option to the `status` command

**Review by smithfarm — APPROVED** [review]

**Comment by ricardoasmarques** [comment]
> ...
> 
> Thanks! I checked again and It's actually the undefined variable `bootstrap_minion` in pillar (as the minion log in #84) makes minions reply error when running `salt -G 'ceph-salt:member' state.sls_exists ceph-salt`. So it can't reach the check here yet to print useful message: https://github.com/ceph/ceph-salt/pull/112/files#diff-d5595865bb360e37be437f3b1446834cR1268-R1273

@bk201  Good catch! Should be fixed now, thanks.

**Review by bk201 — APPROVED** [review]
Thanks! The new changes work!

**Pull request merged**
