### PR TITLE
Add Jenkinsfile.integration

### PR DESCRIPTION
**Pull request by toabctl**
Do PR testing with sesdev[1] and trigger the sesdev integration
pipeline[2] when a new ceph-salt PR is created.

Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

### CODE REVIEW

**Comment by sebastian-philipp** [comment]
blocked by the hanging bootstrap, right? cc @smithfarm

**Comment by toabctl** [comment]
> blocked by the hanging bootstrap, right? cc @smithfarm

yes. but I'm also not yet sure if this is the right approach. And it's not yet testing the PR itself. just using git master...

**Comment by toabctl** [comment]
trying something different...

**Comment by toabctl** [comment]
@sebastian-philipp @ricardoasmarques @smithfarm together with https://github.com/SUSE/sesdev/pull/190 , this seems to work now. Could you review please?

**Comment by toabctl** [comment]
Depends on https://github.com/SUSE/sesdev/pull/197

**Review by ricardoasmarques — APPROVED** [review]
lgtm

**Pull request merged**
