### PR TITLE
provision-begin.sls: work around podman/runc bug

### PR DESCRIPTION
**Pull request by smithfarm**
Works-around: https://github.com/ceph/ceph-salt/issues/130
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
I can confirm that this makes the needed modification to the file:

```
2020-03-20 11:40:49,792 [salt.state       :1821][INFO    ][12947] Running state [/usr/lib/systemd/system/salt-minion.service] at time 11:40:49.792628
2020-03-20 11:40:49,793 [salt.state       :1854][INFO    ][12947] Executing state file.line for [/usr/lib/systemd/system/salt-minion.service]
2020-03-20 11:40:49,805 [salt.state       :321 ][INFO    ][12947] File changed:
---
+++
@@ -3,7 +3,7 @@
 After=network.target salt-master.service

 [Service]
-Type=notify
+#Type=notify
 NotifyAccess=all
 LimitNOFILE=8192
```
and

```
2020-03-20 11:40:49,805 [salt.state       :1821][INFO    ][12947] Running state [/usr/lib/systemd/system/salt-minion.service] at time 11:40:49.805920
2020-03-20 11:40:49,806 [salt.state       :1854][INFO    ][12947] Executing state file.line for [/usr/lib/systemd/system/salt-minion.service]
2020-03-20 11:40:49,808 [salt.state       :321 ][INFO    ][12947] File changed:
---
+++
@@ -4,7 +4,7 @@

 [Service]
 #Type=notify
-NotifyAccess=all
+#NotifyAccess=all
 LimitNOFILE=8192
 ExecStart=/usr/bin/salt-minion
```

However, it doesn't work because the `salt-minion.service` needs to be restarted after the file is modified, and I don't know how to do that from within a Salt State :-(

**Comment by smithfarm** [comment]
The file needs to be munged (and `salt-minion.service` restarted) **before** the Salt States begin executing.

**Comment by smithfarm** [comment]
Apparently, it *is* possible to restart the `salt-minion.service` using States:

https://docs.saltstack.com/en/latest/faq.html#restart-using-states

**Comment by sebastian-philipp** [comment]
```
salt '*' cmd.run 'unset NOTIFY_SOCKET; podman run --net=host --rm registry.opensuse.org/opensuse/leap:15.2 bash -c "seq 5080 | awk '"'"'{print 12345678901234567890}'"'"' "'
<works>
```

I think `unset NOTIFY_SOCKET;` is less intrusive?

**Comment by bk201** [comment]
> 
> I think `unset NOTIFY_SOCKET;` is less intrusive?

Seems work too: https://paste.opensuse.org/view/raw/38547391

**Comment by smithfarm** [comment]
> I think `unset NOTIFY_SOCKET;` is less intrusive?

So we put that before the `cephadm bootstrap` call?

**Comment by smithfarm** [comment]
@bk201 Nice! Closing this one, then.

**Comment by ricardoasmarques** [comment]
> > I think `unset NOTIFY_SOCKET;` is less intrusive?
> 
> Seems work too: https://paste.opensuse.org/view/raw/38547391

@bk201 I've created a PR with your patch https://github.com/ceph/ceph-salt/pull/134

**Pull request closed without merging**
